name: Build and Deploy
on:
  push:
    branches:
      - main  # Replace with your default branch if not "main"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build  # Replace with your build command if different

    - name: Archive Production Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist  # Replace with your build output directory if different

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
